"use client";

import { motion } from "framer-motion";
import { Code2, Ban, Users, CheckCircle, Brain } from "lucide-react";

const principles = [
  {
    number: "01",
    title: "Code-Level Accountability",
    icon: Code2,
    color: "text-primary",
    bg: "bg-primary/10",
    description:
      "I stand behind every architectural adjustment because I write and debug it directly. I don&apos;t give advice I wouldn&apos;t be comfortable deploying into a production branch myself.",
    bullets: [
      "All audits accompanied by functional code snippets or Pull Requests",
      "Staging environment reproduction steps for all identified bugs",
    ],
  },
  {
    number: "02",
    title: "AEO/GEO Integrity",
    icon: Brain,
    color: "text-green-600 dark:text-green-400",
    bg: "bg-green-100 dark:bg-green-900/20",
    description:
      "No empty ranking guarantees, no PBN spam, and no dubious promises of &quot;guaranteed #1 citations in ChatGPT.&quot; I optimize the verifiable signals that AI agents and search engines require — structured data, entity accuracy, and authoritative sourcing.",
    bullets: [
      "Grounding in official documentation and verified crawler behavior",
      "Honest upfront assessments of AEO/GEO architectural limitations",
    ],
  },
  {
    number: "03",
    title: "Zero Automated Fluff",
    icon: Ban,
    color: "text-orange-600 dark:text-orange-400",
    bg: "bg-orange-100 dark:bg-orange-900/20",
    description:
      "You will never receive a generic 80-page export generated by an automated SaaS tool and labeled as an audit. Every line of my deliverables is tailored to your unique codebase, framework constraints, and business model.",
    bullets: [
      "Prioritized, severity-ranked backlogs based on crawl ROI",
      "Clear separation between critical blockers and minor cosmetic items",
    ],
  },
  {
    number: "04",
    title: "Developer-Friendly Collaboration",
    icon: Users,
    color: "text-purple-600 dark:text-purple-400",
    bg: "bg-purple-100 dark:bg-purple-900/20",
    description:
      "I respect your sprint cadence, branch protections, pull request conventions, and code review standards. I don&apos;t disrupt your release train; I integrate directly into Jira, Linear, or GitHub issues as a frictionless partner.",
    bullets: [
      "Ticket acceptance criteria written in engineering syntax",
      "Asynchronous async-first updates across global time zones",
    ],
  },
];

export function Principles() {
  return (
    <section className="w-full py-16 lg:py-24" aria-label="Working principles and values">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col gap-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="max-w-3xl flex flex-col gap-3"
        >
          <span className="font-mono text-xs text-primary uppercase tracking-wider font-semibold">
            Integrity &amp; Engineering Standards
          </span>
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">
            Four Principles That Define Every Client Engagement.
          </h2>
          <p className="text-muted-foreground text-lg">
            In an industry cluttered with vague buzzwords, black-box guarantees, and automated report
            mills, I hold my work to clear, verifiable engineering standards — including honest
            AEO/GEO assessments.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {principles.map((p, index) => {
            const Icon = p.icon;
            return (
              <motion.div
                key={p.number}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="p-8 rounded-2xl bg-card border border-border shadow-sm flex flex-col gap-4"
              >
                <div className={`w-12 h-12 rounded-xl bg-muted flex items-center justify-center ${p.color}`}>
                  <Icon className="h-6 w-6" />
                </div>
                <div className="flex items-center gap-2">
                  <span className={`font-mono text-sm font-bold ${p.color}`}>{p.number}</span>
                  <h3 className="text-xl font-bold">{p.title}</h3>
                </div>
                <p className="text-muted-foreground leading-relaxed">{p.description}</p>
                <ul className="text-sm text-foreground flex flex-col gap-2 pt-2">
                  {p.bullets.map((bullet, i) => (
                    <li key={i} className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-600 dark:text-green-400 flex-shrink-0" />
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
