"use client";

import { motion } from "framer-motion";
import {
  Clock,
  CheckCircle2,
  Shield,
  TrendingDown,
  ShieldAlert,
  BarChart3,
  FileWarning,
  Calendar,
  GitBranch,
  RefreshCw,
  MoveRight,
} from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const models = [
  {
    number: "01",
    title: "Technical Audit & Fix Sprint",
    timeline: "2 to 4 Weeks",
    icon: Clock,
    checklist: [
      "Full Screaming Frog, CrUX & log inspection",
      "Prioritized task tickets ready for sprint planning",
      "Direct PR submission or pairing with your devs",
    ],
    cta: "Book Audit Sprint",
    featured: false,
  },
  {
    number: "02",
    title: "Retained Technical Advisory & QA",
    timeline: "Monthly Partnership",
    icon: RefreshCw,
    checklist: [
      "Weekly automated crawl regression testing",
      "Staging site QA before every major feature release",
      "Continuous AEO & schema graph maintenance",
    ],
    cta: "Retain Technical Advisory",
    featured: true,
  },
  {
    number: "03",
    title: "Zero-Traffic-Loss Migration & Build",
    timeline: "Project-Based",
    icon: MoveRight,
    checklist: [
      "1:1 URL mapping matrix with regex wildcards",
      "Pre-launch and post-launch crawl parity validation",
      "Edge redirect rule deployment (Cloudflare / Vercel)",
    ],
    cta: "Plan Site Migration",
    featured: false,
  },
];

const boundaries = [
  {
    label: "NO BACKLINK SPAM",
    icon: TrendingDown,
    description:
      "No PBNs, no link farms, no automated directory submissions.",
  },
  {
    label: "NO AUTOMATED CHECKLISTS",
    icon: FileWarning,
    description:
      "Every audit is hand-analyzed, not generated by a plugin template.",
  },
  {
    label: "NO RANKING GUARANTEES",
    icon: ShieldAlert,
    description:
      "No one can ethically guarantee rankings. I guarantee engineering rigor.",
  },
  {
    label: "NO VANITY METRICS",
    icon: BarChart3,
    description:
      "I report on revenue impact and crawl health, not hollow traffic graphs.",
  },
];

export default function ServicesEngagementModels() {
  return (
    <section className="bg-accent/20 py-20 lg:py-32">
      <div className="max-w-7xl mx-auto px-6 lg:px-12">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-1.5 mb-6">
            <span className="text-xs font-mono tracking-widest uppercase text-secondary">
              Predictable Collaboration
            </span>
          </div>

          <h2 className="text-3xl lg:text-5xl font-bold tracking-tight mb-6">
            Three Transparent Engagement Models
          </h2>

          <p className="text-lg text-foreground/70 max-w-3xl mx-auto leading-relaxed">
            Choose the format that fits your engineering team&apos;s current
            velocity and organizational structure.
          </p>
        </motion.div>

        {/* Model Cards */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-20">
          {models.map((model, index) => (
            <motion.div
              key={model.number}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.6, delay: index * 0.15 }}
              className={`relative p-8 rounded-2xl bg-card border shadow-sm flex flex-col ${
                model.featured
                  ? "border-secondary ring-1 ring-secondary/20"
                  : "border-border"
              }`}
            >
              {model.featured && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                  <span className="inline-block rounded-full bg-secondary px-4 py-1 text-[10px] font-mono font-bold tracking-widest uppercase text-secondary-foreground">
                    Most Requested
                  </span>
                </div>
              )}

              {/* Model Number & Title */}
              <div className="mb-6">
                <div className="flex items-center gap-3 mb-3">
                  <span className="text-xs font-mono tracking-widest text-muted-foreground">
                    Model {model.number}
                  </span>
                  <model.icon className="w-4 h-4 text-secondary" />
                </div>
                <h3 className="text-xl font-bold leading-snug">
                  {model.title}
                </h3>
              </div>

              {/* Timeline */}
              <div className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-3 py-1.5 mb-6 self-start">
                <Calendar className="w-3.5 h-3.5 text-secondary" />
                <span className="text-xs font-mono text-muted-foreground">
                  {model.timeline}
                </span>
              </div>

              {/* Checklist */}
              <ul className="space-y-3 mb-8 flex-1">
                {model.checklist.map((item, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <CheckCircle2 className="w-4 h-4 text-secondary shrink-0 mt-0.5" />
                    <span className="text-sm text-muted-foreground leading-relaxed">
                      {item}
                    </span>
                  </li>
                ))}
              </ul>

              {/* CTA */}
              <Button
                asChild
                variant={model.featured ? "default" : "outline"}
                className="w-full"
              >
                <Link href="/contact">{model.cta}</Link>
              </Button>
            </motion.div>
          ))}
        </div>

        {/* Honest Boundaries Box */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="rounded-2xl border border-border bg-card shadow-sm p-8 lg:p-12"
        >
          <div className="flex items-center gap-3 mb-4">
            <Shield className="w-5 h-5 text-secondary" />
            <h3 className="text-xl font-bold">
              What I Do NOT Do (Professional Boundaries)
            </h3>
          </div>

          <p className="text-muted-foreground leading-relaxed mb-8 max-w-3xl">
            To maintain engineering excellence and protect client reputations, I
            do not engage in standard marketing agency shortcuts.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {boundaries.map((boundary) => (
              <div
                key={boundary.label}
                className="rounded-xl border border-border bg-background p-5"
              >
                <boundary.icon className="w-5 h-5 text-secondary mb-3" />
                <span className="block text-xs font-mono font-bold tracking-widest uppercase mb-2">
                  {boundary.label}
                </span>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  {boundary.description}
                </p>
              </div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
